I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call day1
  File "game/script.rpy", line 80, in script
    with fade(3.0)
TypeError: 'MultipleTransition' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call day1
  File "game/script.rpy", line 80, in script
    with fade(3.0)
  File "/home/ellis/Downloads/renpy-8.0.3-sdk/renpy/ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "/home/ellis/Downloads/renpy-8.0.3-sdk/renpy/exports.py", line 1657, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/ellis/Downloads/renpy-8.0.3-sdk/renpy/display/core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "/home/ellis/Downloads/renpy-8.0.3-sdk/renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/ellis/Downloads/renpy-8.0.3-sdk/renpy/display/core.py", line 3752, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'MultipleTransition' object is not callable

Linux-5.4.0-144-generic-x86_64-with-glibc2.31 x86_64
Ren'Py 8.0.3.22090809
Mafia Dating Sim 1.0
Sun Mar 19 17:25:15 2023
